[package]
name = "sakura"
version = "0.1.0"
edition = "2021"
author = ["shotgunck"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
dotenv = "0.15.0"
futures-util = { default-features = false, version = "0.3" }
image = "0.23.14"
reqwest = { version = "0.11", features = ["json"] }
rocket = "0.4.2"
serde = "1.0.130"
tokio = { features = ["macros", "rt-multi-thread"], version = "1.0" }
twilight-gateway = "0.8.0"
twilight-http = "0.8.0"
twilight-lavalink = "0.8.0"
twilight-model = "0.8.0"
twilight-standby = "0.8.0"
twilight-command-parser = "0.8.0"
twilight-cache-inmemory = "0.8.0"
twilight-embed-builder = "0.8.0"

[dependencies.songbird]
version = "0.2.0-beta.3"
default-features = false
features = ["driver", "twilight-rustls", "zlib-stock"]